[package]
name = "fgl"
description = "Fr13nd Gtk Library"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8"
gtk4-layer-shell = "0.3"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
network-manager = "0.11"
notify = "6.1.1"
notify-debouncer-full = "0.3"
